### ISSUE TITLE
Pull&Run missing

### ISSUE THREAD

**Issue by fr4ncidir** [lroffia/iotgateway#1]
Project 'IoTGateway' is missing required Java project: 'STDash7'

**Comment by fr4ncidir** [comment]
IoTGateway seems not compliant to SEPATools Project
![screenshot at 2017-02-26 15 20 54](https://cloud.githubusercontent.com/assets/12054631/23340472/36112090-fc37-11e6-8611-5d7c487f9c58.png)

**Comment by lroffia** [comment]
Can you try again? I pushed an updated IoT project

**Comment by fr4ncidir** [comment]
Seems solved :+1:
